---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICFjCCAb2gAwIBAgIUEaq8rlSVtg+sudYvQREFV0ggPVEwCgYIKoZIzj0EAwIw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTI1MTAwMTE1MzAwMFoXDTQwMDkyNzE1MzAwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAET/vqG1BbThe8IpCfk1t+r9Gx
          CJm9pdZJgmZhx7RbHYWkl3pltzVTVnxWqMnx3bI2zlKqX49MZtmx/8k9z60aiaNF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FMSR8ggC+kXZ2whs3z6o9EPNwBR9MAoGCCqGSM49BAMCA0cAMEQCIBsnBClG6pkE
          hM/Z8rpxXtNtFQ5VzflFBjRkclBXqPS4AiBKWuSd/bZJHDoO0SRIpT31wdquKJJR
          M3HcYsOSCGO9Ng==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICFjCCAb2gAwIBAgIUEaq8rlSVtg+sudYvQREFV0ggPVEwCgYIKoZIzj0EAwIw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTI1MTAwMTE1MzAwMFoXDTQwMDkyNzE1MzAwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAET/vqG1BbThe8IpCfk1t+r9Gx
          CJm9pdZJgmZhx7RbHYWkl3pltzVTVnxWqMnx3bI2zlKqX49MZtmx/8k9z60aiaNF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FMSR8ggC+kXZ2whs3z6o9EPNwBR9MAoGCCqGSM49BAMCA0cAMEQCIBsnBClG6pkE
          hM/Z8rpxXtNtFQ5VzflFBjRkclBXqPS4AiBKWuSd/bZJHDoO0SRIpT31wdquKJJR
          M3HcYsOSCGO9Ng==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
