---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUPbU5A94Jso62Sz/8ClZpuSUG7DUwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUwOTExMTYzMjAwWhcNNDAwOTA3MTYzMjAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFo3
          P9CLilNd2ns/KiIF9H09ETexn7eKjc0m6GWdPVdpdVF2xX3Pka0aiDBqJpBJQ/wK
          a7rlCwHSDmVPCXUAZYWjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSsdANSr/AbnN803H2+2ci+qP0LyTAKBggqhkjOPQQD
          AgNIADBFAiEAioJjqjtIhlYfD7LIfjjgBsSPkl+4yulhfuZaJw7+CWsCIDz4tcnw
          6OzhgfXIVTcCMajsX4588fRtEqiZ5mKeyovl
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUPbU5A94Jso62Sz/8ClZpuSUG7DUwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUwOTExMTYzMjAwWhcNNDAwOTA3MTYzMjAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFo3
          P9CLilNd2ns/KiIF9H09ETexn7eKjc0m6GWdPVdpdVF2xX3Pka0aiDBqJpBJQ/wK
          a7rlCwHSDmVPCXUAZYWjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSsdANSr/AbnN803H2+2ci+qP0LyTAKBggqhkjOPQQD
          AgNIADBFAiEAioJjqjtIhlYfD7LIfjjgBsSPkl+4yulhfuZaJw7+CWsCIDz4tcnw
          6OzhgfXIVTcCMajsX4588fRtEqiZ5mKeyovl
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
