---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUbojNmKRrpf4DzsrAehheq5uI83EwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUwOTE3MTUyMDAwWhcNNDAwOTEzMTUyMDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPCt
          k/p2vL0qcwiJqzfl8nFBuu5piTSI7tkpHpRIun5Yq3c9/8VF+tTkhCgJXUY9DVOn
          tiJw7b0mvVoAlUaC6vWjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSCaW3nG13GtS6WBrWa7tl2NaxAGjAKBggqhkjOPQQD
          AgNHADBEAiABbf/3Yvco8roA2KTCQ9oy/o/OA8yDKQVqGgYCiiErjAIgco9VCg1y
          QEy2hJFc7HL2XXrpL1T2DitJ45RiTLo8uJ4=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUbojNmKRrpf4DzsrAehheq5uI83EwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUwOTE3MTUyMDAwWhcNNDAwOTEzMTUyMDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPCt
          k/p2vL0qcwiJqzfl8nFBuu5piTSI7tkpHpRIun5Yq3c9/8VF+tTkhCgJXUY9DVOn
          tiJw7b0mvVoAlUaC6vWjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSCaW3nG13GtS6WBrWa7tl2NaxAGjAKBggqhkjOPQQD
          AgNHADBEAiABbf/3Yvco8roA2KTCQ9oy/o/OA8yDKQVqGgYCiiErjAIgco9VCg1y
          QEy2hJFc7HL2XXrpL1T2DitJ45RiTLo8uJ4=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
