---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUAVceRlRPjOdV2N6aH+wX5Jo7Z54wCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUwOTE2MTEwMDAwWhcNNDAwOTEyMTEwMDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNR1
          1aacoiKkwKuMk0tbFcP6BJ+Rqv2xD2Z7DgdZni7yAiKc381Kj2brMg/3WXx87tZ0
          zOZHf2C/HcW/6xLXmc6jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSps1GjIL5sFG+NCNHQRjwcnimQuDAKBggqhkjOPQQD
          AgNIADBFAiEAiZwZxngIlXVE/yawQOtbufFhWsmLFa+PJKrLJuepN0ICIDuWfY+Q
          Ni7o5Jzf8E6kNHJfH+AIXoVakoYC6eVFOr/S
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUAVceRlRPjOdV2N6aH+wX5Jo7Z54wCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUwOTE2MTEwMDAwWhcNNDAwOTEyMTEwMDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNR1
          1aacoiKkwKuMk0tbFcP6BJ+Rqv2xD2Z7DgdZni7yAiKc381Kj2brMg/3WXx87tZ0
          zOZHf2C/HcW/6xLXmc6jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSps1GjIL5sFG+NCNHQRjwcnimQuDAKBggqhkjOPQQD
          AgNIADBFAiEAiZwZxngIlXVE/yawQOtbufFhWsmLFa+PJKrLJuepN0ICIDuWfY+Q
          Ni7o5Jzf8E6kNHJfH+AIXoVakoYC6eVFOr/S
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
