---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUQVtUKlv9GNY7M4V/6h3lVMNTerEwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUwOTE1MDgxNTAwWhcNNDAwOTExMDgxNTAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCU7
          IiYOpOFhZ/PrNo56ATcbintvTYraV07lXe9L5txOWrKMfFA4UiM71jCIP1fo7y8M
          R5yGAzF5+RRq0FWRNEOjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBS3ToTDutGrwkBf/BtXwjIBKgHvUDAKBggqhkjOPQQD
          AgNIADBFAiEAxkPS5s3AHDcEpPeG1xILJbAV7ARVd0dEoV/YQD6gRBcCIA2sfjdJ
          lgyC2cXMM3NcCHjP1/fnsRInUot/XrQ+jxx+
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUQVtUKlv9GNY7M4V/6h3lVMNTerEwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUwOTE1MDgxNTAwWhcNNDAwOTExMDgxNTAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCU7
          IiYOpOFhZ/PrNo56ATcbintvTYraV07lXe9L5txOWrKMfFA4UiM71jCIP1fo7y8M
          R5yGAzF5+RRq0FWRNEOjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBS3ToTDutGrwkBf/BtXwjIBKgHvUDAKBggqhkjOPQQD
          AgNIADBFAiEAxkPS5s3AHDcEpPeG1xILJbAV7ARVd0dEoV/YQD6gRBcCIA2sfjdJ
          lgyC2cXMM3NcCHjP1/fnsRInUot/XrQ+jxx+
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
