---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUbcMJKGz8cCtXnL2B0k54+WQeLwUwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yNTA5MTcxNTIwMDBaFw00MDA5MTMxNTIwMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARF8ML0RfHiQmK6
          4lL7iAjmjFVpQwgCsUfdO1pJI9y7jKGb3t7wGxdqZUCxNTntARxkAief7MaEhC7H
          6aL4tSvLo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUzuJVJ+F55EjNJSagsYhiAGiSTtgwCgYIKoZIzj0EAwIDRwAwRAIg
          FrUT4wslk/YOU8Oql2pk/6fdElhEKPpmjqoUO+MButQCIByxG4gTJ5vkIYzNJ/O8
          gs5jqPYljC/gfjD/cmxi0+XV
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUbcMJKGz8cCtXnL2B0k54+WQeLwUwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yNTA5MTcxNTIwMDBaFw00MDA5MTMxNTIwMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARF8ML0RfHiQmK6
          4lL7iAjmjFVpQwgCsUfdO1pJI9y7jKGb3t7wGxdqZUCxNTntARxkAief7MaEhC7H
          6aL4tSvLo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUzuJVJ+F55EjNJSagsYhiAGiSTtgwCgYIKoZIzj0EAwIDRwAwRAIg
          FrUT4wslk/YOU8Oql2pk/6fdElhEKPpmjqoUO+MButQCIByxG4gTJ5vkIYzNJ/O8
          gs5jqPYljC/gfjD/cmxi0+XV
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
