---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUbayW13OIEydBzfIywXyMW4LeBLUwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yNTA5MTUwODE1MDBaFw00MDA5MTEwODE1MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATu19rIrbYk9nN6
          H3IMFyjAWU53EI1EOP+y43UOgmvBE6MDosL0yVCYC2tab+1pTD07Oh5HTMAKqQs1
          pWyLDTAdo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUlAHe5ZeoK4q7G6fe9IzKyJozUJkwCgYIKoZIzj0EAwIDRwAwRAIg
          QsihNLS5qsyViidnvgbQktop4zvaJY8Rsjc9hzaEpcACIAMaY3ngNK+V2CJypwtw
          UZLy0fWJf97eM1I8LzmvBIfx
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUbayW13OIEydBzfIywXyMW4LeBLUwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yNTA5MTUwODE1MDBaFw00MDA5MTEwODE1MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATu19rIrbYk9nN6
          H3IMFyjAWU53EI1EOP+y43UOgmvBE6MDosL0yVCYC2tab+1pTD07Oh5HTMAKqQs1
          pWyLDTAdo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUlAHe5ZeoK4q7G6fe9IzKyJozUJkwCgYIKoZIzj0EAwIDRwAwRAIg
          QsihNLS5qsyViidnvgbQktop4zvaJY8Rsjc9hzaEpcACIAMaY3ngNK+V2CJypwtw
          UZLy0fWJf97eM1I8LzmvBIfx
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
