---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUd//ob2EML+h4tGQYsJ33LOQ7erEwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yNTA5MTMxMTA3MDBaFw00MDA5MDkxMTA3MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ4GxKcBSM6IobT
          paz1mYoy71Za20RQjPFC88VRRNu2QOdDqg+/VcbZ0O1am/hO7OVqXZWET/gqf4+Z
          2OroTj/Oo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUy+LhWFRdgR/kujUEPFR5ea1GVBowCgYIKoZIzj0EAwIDRwAwRAIg
          RIR6Ftz/SRGcPDwoy/sbn5IcBiA4M1tKPEdbwCyA9x0CID3fvgL+fw6D/1QnDS/X
          a4We3td4fz3O30QxcvEO4xPy
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUd//ob2EML+h4tGQYsJ33LOQ7erEwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yNTA5MTMxMTA3MDBaFw00MDA5MDkxMTA3MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ4GxKcBSM6IobT
          paz1mYoy71Za20RQjPFC88VRRNu2QOdDqg+/VcbZ0O1am/hO7OVqXZWET/gqf4+Z
          2OroTj/Oo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUy+LhWFRdgR/kujUEPFR5ea1GVBowCgYIKoZIzj0EAwIDRwAwRAIg
          RIR6Ftz/SRGcPDwoy/sbn5IcBiA4M1tKPEdbwCyA9x0CID3fvgL+fw6D/1QnDS/X
          a4We3td4fz3O30QxcvEO4xPy
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
